FILES = \
    BaseDataReader.py  create_batch.py   deleteDataset.py  listDataset.py   \
    RowGroupMap.py  SegmentLoader.py  uprootArray3.py \
    batch.py           createDataset.py  __init__.py       listDatasets.py  \
    run_batch.py    uprootArray33.py  verifyDataset.py

build: $(DSTDIR)
	cp $(FILES) $(DSTDIR)
    
$(DSTDIR):
	mkdir -p $@
    
    


