FILES = buckets.html  dataset.html  dataset_info.html  datasets.html  index.html striped.cfg  template.html \
    StripedServerApp.py  StripedServerApp2.py 

build: $(DSTDIR)
	cp $(FILES) $(DSTDIR)
    
$(DSTDIR):
	mkdir -p $@
    
