FILES = __init__.py MyThread.py  MyTracer.py  registry_interface.py  \
    Stopwatch.py  trace.py DataExchange.py \
    WorkerRequest.py JobDescription.py structures.py Meta.py LogFile.py rfc2617.py \
    signature.py exceptions.py Meta.py tokens.py signed_token.py bulk_data_transport.py dataEncoder.py importer.py

build: $(DSTDIR)
	cp $(FILES) $(DSTDIR)
    
$(DSTDIR):
	mkdir -p $@
    
    


