FILES = \
attribute_setter.py  QAPointers.py  QData2.py   SocketWorker2.py           StripedWorker2.py  Vault.py \
QAFilters.py         QArrays2.py    sandbox.py  \
worker_master.py    BulkStorage.py

build: $(DSTDIR)
	cp $(FILES) $(DSTDIR)
    
$(DSTDIR):
	mkdir -p $@
    



